### ISSUE TITLE
Consistent use and expansion of AA

### ISSUE THREAD

**Issue by pzb** [GSA/dotgov-home#15]
In https://home.dotgov.gov/policy/, the phrase "Authorizing Authority" and acronym "AA" are not used consistently.  AA only needs to be defined at most once per paragraph but should be defined at least once per section.

In the "Local Government Sponsored Domain Guidelines" section, consider replacing "AA (Mayor or Elected Official Authorization)" with "Authorizing Authority (Mayor or Elected Official)".

**Comment by nicoleslaw** [comment]
@konklone This is a similar issue. Do we need to use the acronym at all?

**Comment by konklone** [comment]
Totally fine to expand it.
