### ISSUE TITLE
Develop sitemap

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/dotgov-home#24]

**Comment by nicoleslaw** [comment]
Sharing a rough draft here.

I have some [open questions](https://docs.google.com/document/d/1giexWyAqE90rOWppDfP46kolnx8nNSeDFhCR3jVFPis/edit#) and am probably missing some things. Feel free to comment here or in Slack.

[DotGov_sitemap_v1.pdf](https://github.com/GSA/dotgov-home/files/1209551/DotGov_sitemap_v1.pdf)

cc @konklone @porta-antiporta

**Comment by porta-antiporta** [comment]
posting my comments in :slack:
