### ISSUE TITLE
Start research plan

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/dotgov-home#25]
- [x] Conversation guide
- [x] Potential interviewees list from @konklone 
- [ ] Wiki
- [x] Invitation email

**Comment by nicoleslaw** [comment]
@porta-antiporta I started a [recruiting email draft](https://docs.google.com/document/d/1U8Gm6EC1awvggfNf46p6aSOPtXg_8PGgmoedkUGRTEc/edit#) and a [conversation guide](https://docs.google.com/document/d/1TH9feSEBi3KXE2KtWHPnQYKksI8er5O0hFr1qWzovFQ/edit#) . Would you mind taking a look, and let me know if you have any suggestions?

**Comment by porta-antiporta** [comment]
@nicoleslaw had one question in the convo guide.  The recruiting email looks good.
One thing i forgot is to confirm with you: whether the [consent form](https://docs.google.com/a/gsa.gov/forms/d/1ceSgyjJ_ZwbE8e9uNb7w2lD-iFU4jNp3dNDkitKsL48/edit) that was used for the data scanning stream could be used as is for this stream.  I believe it can be.

**Comment by nicoleslaw** [comment]
Re: consent form: that's awesome—I had cloned one but will use that instead.

**Comment by porta-antiporta** [comment]
What's the wiki going to be used for ^^?

**Comment by nicoleslaw** [comment]
Sharing research findings, user insights, and design recommendations for future iterations. Here's an example from a different project (though we won't need this many pages): https://github.com/18F/crime-data-explorer/wiki/User-Insights

**Comment by nicoleslaw** [comment]
I need to update the wiki, but will do that as part of synthesis given how short on time we are.

**Comment by nicoleslaw** [comment]
Closing this in favor of #27
