### ISSUE TITLE
Links at the top of FAQs for each question

### ISSUE THREAD

**Issue by konklone** [GSA/dotgov-home#3]
The subnav is good for high level section differentiators, but I think it'd still be good to have each question at the top with a link, like https://https.cio.gov/faq/ and https://https.cio.gov/guide/ have -- even if this site's content is temporary and will be rewritten.

**Comment by h-m-f-t** [comment]
Not exactly like https://https.cio.gov, but this was done for our requirements page. We did add FAQs at the top for our [domain registration](https://home.dotgov.gov/registration/common-questions/) and [domain management](https://home.dotgov.gov/management/) FAQs.
