### ISSUE TITLE
Simplify the naming schema

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/dotgov-home#32]
So many similar words! Make a naming/branding recommendation.

- Is it a registry or a program or a service?
- When to use `.gov`
- Is it `dotgov.gov` or `DotGov.gov` or `DotGov` etc.?
- When to use `.gov domains` (thinking this is only for talking about the whole of .gov URLs or a specific one you need to set up)

I am also seeing `dotgov sites` and `the Dotgov site` — and these are super confusing.

As James noted:

> saying “dot gov dot gov” is enjoyable, which makes me think `dotgov.gov` could catch on even more easily than `DotGov`

Kinda leaning toward DotGov.gov for the wordmark, but I will leave that to Amber and Maya.

**Comment by konklone** [comment]
> Is it a registry or a program or a service?

The DotGov program operates the .gov registry.

> When to use .gov domains (thinking this is only for talking about the whole of .gov URLs or a specific one you need to set up)

".gov domains" refers to registered domains, but is distinct from (not synonymous or a superset or a subset of) ".gov websites". The list of .gov domains is here:

https://github.com/GSA/data/blob/gh-pages/dotgov-domains/current-full.csv

And there are ~5,600 of them. That list is the only thing that ".gov domains" means. You might refer to a single ".gov domain" in a variety of contexts, including registration/administration, but also certain domain-wide properties that transcend individual sites or services hosted on the domain (such as its CAA record or preloaded HSTS/HPKP policies).

> I am also seeing `dotgov sites` and the `Dotgov site` — and these are super confusing.

Yeah, I would never use `dotgov sites`, and would only ever say `.gov sites`. `.gov` is a factual matter, and `DotGov`/`dotgov` is a brand.

(Not trying to shut down further conversation about this, only ringing in when I think there's a clear objective answer to certain clarifying questions.)

**Comment by h-m-f-t** [comment]
@konklone's disambiguation is 👍👍 

"DotGov" is often used to describe the policy and management authority that runs the TLD, where ".gov" is the technical infrastructure: the registrar and registry.

We tried to capture some of this nuance in https://home.dotgov.gov/about/.
