### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by llupis** [GSA/dotgov-home#54]
Ideally, it should probably have a site search per Digital Gov Checklist at: https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/#search.   

That page gives the appearance it is a Fed requirement, but not 100% positive.  So, I just wanted to report that.  

Thanks.

**Comment by line47** [comment]
Search.gov could be added to the site, https://github.com/18F/uswds-jekyll#search  after updating your version of the `uswds-jekyll` gem

**Comment by lachellel** [comment]
min viable in #80 
closing

**Comment by smarina04** [comment]
Search functionality was added to home.dotgov.gov.
