### ISSUE TITLE
HSTS

### ISSUE THREAD

**Issue by llupis** [GSA/dotgov-home#55]
I also wanted to report that apparently due to an invalid redirect, the site may lose HSTS Preload compliance.  Please see the following for more info.  Thanks!

https://hstspreload.org/?domain=dotgov.gov

**Comment by h-m-f-t** [comment]
@llupis, thanks. We're aware of this, but appreciate your help cataloging it.

**Comment by h-m-f-t** [comment]
We're tracking this, and will have straight redirects in January 2019. Closing this on the repo for now.
