### ISSUE TITLE
Use whole words instead of acronyms for "TLD" on the home page in order to help new visitors understand the site's purpose

### ISSUE THREAD

**Issue by jenniferthibault** [GSA/dotgov-home#75]
Acronyms can confuse readers who aren't already extremely familiar with the content or context of your site. You can make your site more welcoming and inclusive for less-familiar perspectives if you avoid using acronyms, or introduce them in the long form the first time they're used on a page.

Check out the 18F Content Guide for more on [Abbreviations and acronyms](https://content-guide.18f.gov/abbreviations-and-acronyms/)

(I'd submit a PR to fix this myself, but I don't actually know what `TLD` stands for, sorry!)

**Comment by h-m-f-t** [comment]
Thanks for the nudge, @jenniferthibault. 👍🇺🇸 

(TLD means "top-level domain". Check out https://home.dotgov.gov/about/ for more info.)

**Comment by jenniferthibault** [comment]
Woo! Thanks!
